" VIM Plug and plugins
" --------------------
call plug#begin()
    Plug 'Konfekt/FastFold'
    Plug 'Raimondi/delimitMate'
    Plug 'SidOfc/mkdx'
    Plug 'christoomey/vim-tmux-navigator'
    Plug 'dense-analysis/ale'
    Plug 'edkolev/tmuxline.vim'
    Plug 'ervandew/supertab'
    Plug 'godlygeek/tabular'
    Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install' }
    Plug 'jeetsukumaran/vim-buffergator'
    Plug 'jeetsukumaran/vim-pythonsense'
    Plug 'johmsalas/text-case.nvim'
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'
    Plug 'ludovicchabant/vim-gutentags'
    Plug 'mileszs/ack.vim'
    Plug 'mzlogin/vim-markdown-toc'
    Plug 'neovim/nvim-lspconfig'
    Plug 'preservim/nerdcommenter'
    Plug 'preservim/nerdtree'
    Plug 'preservim/nerdtree'
    Plug 'preservim/tagbar'
    Plug 'preservim/vimux'
    Plug 'tmhedberg/SimpylFold'
    Plug 'tpope/vim-fugitive'
    Plug 'tpope/vim-sensible'
    Plug 'tpope/vim-surround'
    Plug 'tpope/vim-unimpaired'
    Plug 'tridactyl/vim-tridactyl'
    Plug 'vim-airline/vim-airline'
    Plug 'xolox/vim-misc'
    Plug 'ycm-core/YouCompleteMe'

    "" Themes
    Plug 'zeekay/vice-colorful'
    Plug 'vim-airline/vim-airline-themes'

    "" Syntax
    Plug 'martinda/Jenkinsfile-vim-syntax'
call plug#end()

" In-built plugins
packadd cfilter

" GUI settings
" ------------
set termguicolors
set t_Co=256
set t_ut=
colorscheme xoria256
set bg=dark

set colorcolumn=88 tw=88
set nowrap

set ruler wildmenu hidden visualbell noerrorbells mousehide
set history=1000
set undolevels=1000
set scrolloff=3
set shortmess=atI
set wildmenu wildmode=list:longest
set wildignore=*.swp,*.bak,*.pyc,*.class,tags
set noswapfile

set foldmethod=syntax
set foldopen-=search
set nofoldenable

" Cursor
let &t_EI = "\033[2 q" " NORMAL  █
let &t_SI = "\033[5 q" " INSERT  |

" Vim text settings
" -----------------
filetype indent plugin on
syntax on
set ffs=unix,mac,dos " Support all three fileformats, in this order
set encoding=utf-8

" Behaviour settings
" ------------------
" Coding style preferences
"set expandtab tabstop=8 softtabstop=4 shiftwidth=4 " Defaults to mixed mode
set expandtab tabstop=4 softtabstop=4 shiftwidth=4 " Defaults to mixed mode
set shiftround
set smarttab
set autoindent copyindent
set backspace=indent,eol,start

" Search behaviour
set incsearch
set ignorecase smartcase
set gdefault
set hlsearch

" Ignore directories when searching
set wildignore+=**/node_modules/**,**/vendor/**,**/__pycache__/**,**/.*_cache/**

" Auto redraw if necessary
au FocusGained * :redraw!

" Macros and keymapping
" ---------------------
" Map leader
let mapleader=","

" Motion mappings
nnoremap ' `
nnoremap ` '
map H ^
map L $
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>
nnoremap <C-Tab> gt
nnoremap <Leader>rts :%s/\s\+$/<CR>
nnoremap <silent> <Leader>nh :silent :nohlsearch<CR>
nnoremap <Leader>dos :set fileformat=dos<CR>
nnoremap <Leader>unix :set fileformat=unix<CR>
nmap . .`[

" Folding mappings
nnoremap <silent> <Leader>f1 :set foldlevel=1<CR>
nnoremap <silent> <Leader>f2 :set foldlevel=2<CR>
nnoremap <silent> <Leader>f3 :set foldlevel=3<CR>
nnoremap <silent> <Leader>fa :set foldlevel=0<CR>
nnoremap <silent> <Leader>f0 :set foldlevel=999<CR>
nnoremap <silent> <Space> za

" Replacement patterns
inoremap qq <Esc>

" Formatting
vmap Q gq
nmap Q gqap

" Forget the arrow keys!!!
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

" Autocompletion
:inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

" Mappings for plugins
nnoremap <Leader>w :set wrap!<CR>

" Sudo save - when I forget to sudo before editing the file
cmap w!! w !sudo tee % > /dev/null

" Tab patterns
" Mixed mode - half tabs are spaces
nnoremap <Leader>0t :set noexpandtab tabstop=8 softtabstop=4 shiftwidth=4<CR>
nnoremap <Leader>2t :set expandtab tabstop=2 shiftwidth=2 softtabstop=2<CR>
nnoremap <Leader>4t :set expandtab tabstop=4 shiftwidth=4<CR>
nnoremap <Leader>4ft :set noexpandtab tabstop=4 softtabstop=4 shiftwidth=4<CR>
nnoremap <Leader>8t :set expandtab tabstop=8 shiftwidth=8<CR>
nnoremap <Leader>8ft :set noexpandtab tabstop=8 softtabstop=8 shiftwidth=8<CR>

" Line swapping
function! s:swap_lines(n1, n2)
    let line1 = getline(a:n1)
    let line2 = getline(a:n2)
    call setline(a:n1, line2)
    call setline(a:n2, line1)
endfunction

function! s:swap_up()
    let n = line('.')
    if n == 1
	return
    endif

    call s:swap_lines(n, n - 1)
    exec n - 1
endfunction

function! s:swap_down()
    let n = line('.')
    if n == line('$')
	return
    endif

    call s:swap_lines(n, n + 1)
    exec n + 1
endfunction

noremap <silent> <c-s-k> :call <SID>swap_up()<CR>
noremap <silent> <c-s-j> :call <SID>swap_down()<CR>

" Toggle spell checking
let g:SpellEnabled=0
function! ToggleSpell()
    if g:SpellEnabled == 0
        setlocal spell spelllang=en_gb
    else
        setlocal nospell
    endif
    let g:SpellEnabled = !g:SpellEnabled
endfunction
nmap <silent> <F7> :call ToggleSpell()<CR>

" Abbrevations
" - expand("%:t") = refer to :help filename-modifiers
iabbr xxsign Seh Hui Leong
iabbr xxdate <C-R>=strftime("%Y-%m-%d")<CR>
iabbr xxdtime <C-R>=strftime("%Y-%m-%d %H:%M:%S")<CR>
iabbr xxpath <C-R>=expand("%")<CR>
iabbr xxfn <C-R>=expand("%:t")<CR>

" Customization for plugins
" -------------------------
" ** NERDTree
let NERDTreeIgnore=[
\  '\.a$', '\.o$', '\.swp$', '\~$',
\  '^tags', '^tags.\(lock\|temp\)$',
\  '\.pyc$', '__pycache__', '^\..*_cache$', '^.pytest.*',
\  '.git$'
\]
let NERDTreeShowHidden=1
let NERDTreeChDirMode=2
nmap <silent> <Leader>tr :NERDTreeToggle<CR>

" ** Supertab
let g:SuperTabDefaultCompletionType="context"

" ** NERDCommenter
map <leader>x <plug>NERDCommenterToggle

" ** Airline
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tagbar#enabled = 0
let g:airline_powerline_fonts = 1
set laststatus=2

" ** ALE
let g:ale_fix_on_save = 1
let g:ale_completion_enabled = 1
let g:ale_fixers = {
\  '*': ['remove_trailing_lines', 'trim_whitespace'],
\}

" ** Jedi.vim
let g:jedi#popup_on_dot = 0

" ** Tagbar
nnoremap <Leader>tb :TagbarToggle<CR>

" ** VIM Wiki
let g:vimwiki_list = [{'path': '~/OneDrive/vimwiki/',
                      \'syntax': 'markdown', 'ext': '.wiki'}]
" ** Snipmate
let g:snipMate = { 'snippet_version' : 1 }

" ** fzf
nnoremap <leader>p :Files<CR>

" ** vim-notes
let g:notes_directories = ['~/Documents/vimnotes',]

" ** ack.vim
" Use ripgrep for searching ⚡️
" Options include:
" --vimgrep -> Needed to parse the rg response properly for ack.vim
" --type-not sql -> Avoid huge sql file dumps as it slows down the search
" --smart-case -> Search case insensitive if all lowercase pattern, Search case
"  sensitively otherwise
let g:ackprg = 'rg --vimgrep --type-not sql --smart-case'

" Any empty ack search will search for the work the cursor is on
let g:ack_use_cword_for_empty_search = 1

" Don't jump to first match
cnoreabbrev Ack Ack!

" Maps <leader>/ so we're ready to type the search keyword
nnoremap <Leader>/ :Ack!<Space>
" }}}

" Navigate quickfix list with ease
nnoremap <silent> [q :cprevious<CR>
nnoremap <silent> ]q :cnext<CR>

" text-case.nvim
nnoremap gas :lua require('textcase').current_word('to_snake_case')<CR>
nnoremap gab :lua require('textcase').current_word('to_dash_case')<CR>
nnoremap gan :lua require('textcase').current_word('to_constant_case')<CR>
nnoremap gad :lua require('textcase').current_word('to_dot_case')<CR>
nnoremap gaa :lua require('textcase').current_word('to_phrase_case')<CR>
nnoremap gac :lua require('textcase').current_word('to_camel_case')<CR>
nnoremap gap :lua require('textcase').current_word('to_pascal_case')<CR>
nnoremap gat :lua require('textcase').current_word('to_title_case')<CR>

nnoremap ges :lua require('textcase').operator('to_snake_case')<CR>
nnoremap geb :lua require('textcase').operator('to_dash_case')<CR>
nnoremap gen :lua require('textcase').operator('to_constant_case')<CR>
nnoremap ged :lua require('textcase').operator('to_dot_case')<CR>
nnoremap gea :lua require('textcase').operator('to_phrase_case')<CR>
nnoremap gec :lua require('textcase').operator('to_camel_case')<CR>
nnoremap gep :lua require('textcase').operator('to_pascal_case')<CR>
nnoremap get :lua require('textcase').operator('to_title_case')<CR>

nnoremap gaS :lua require('textcase').lsp_rename('to_snake_case')<CR>
nnoremap gaB :lua require('textcase').lsp_rename('to_dash_case')<CR>
nnoremap gaN :lua require('textcase').lsp_rename('to_constant_case')<CR>
nnoremap gaD :lua require('textcase').lsp_rename('to_dot_case')<CR>
nnoremap gaA :lua require('textcase').lsp_rename('to_phrase_case')<CR>
nnoremap gaC :lua require('textcase').lsp_rename('to_camel_case')<CR>
nnoremap gaP :lua require('textcase').lsp_rename('to_pascal_case')<CR>
nnoremap gaT :lua require('textcase').lsp_rename('to_title_case')<CR>

" YouCompleteMe
let g:ycm_key_list_stop_completion = ['<C-y>', '<C-t>', '<CR>']

" FastFold
let g:fastfold_savehook = 1
let g:fastfold_fold_command_suffixes =  ['x','X','a','A','o','O','c','C']
let g:fastfold_fold_movement_commands = [']z', '[z', 'zj', 'zk']
let g:yaml_fold = 1

" Buffergator
let g:buffergator_viewport_split_policy="T"

" mzlogin/vim-markdown-toc
let g:vmt_fence_text = "TOC"
let g:vmt_fence_closing_text = "/TOC"
